""" ======================
""" Use Vim settings, rather then Vi settings (much better!).
""" This must be first, because it changes other options as a side effect.
set nocompatible
set autoread
set ruler
set showcmd
set lazyredraw
set nocursorline

" Show matching bracets when text indicator is over them
set showmatch

"=========Backup and restoring 
set dir=./.backup,~/.vim/backup_files,/tmp
silent execute '!mkdir -p $HOME/.vim/tmp/{backup,swap,view,undo}'
set backupdir=$HOME/.vim/tmp/backup/
set backup
set directory=$HOME/.vim/tmp/swap/
set viewdir=$HOME/.vim/tmp/view/
" store undo files, undo edits after deleting a buffer
"set undodir=$HOME/.vim/tmp/undo/
"set undofile
set viminfo='50,n$HOME/.vim/tmp/viminfo

scriptencoding utf-8
set termencoding=utf-8
set encoding=utf-8
set backspace=indent,eol,start
" show the cursor postion all the time


let mapleader = ","
let g:mapleader = ","

" Search options

set incsearch
set ignorecase
set smartcase
set hlsearch

set nu
if has("syntax")
    syntax on
endif


filetype plugin indent on
" Indentation 
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
"  Switching indentation schemas
nmap \t :set expandtab tabstop=4 shiftwidth=4 softtabstop=4<CR>
nmap \T :set expandtab tabstop=8 shiftwidth=8 softtabstop=4<CR>
nmap \M :set noexpandtab tabstop=8 softtabstop=4 shiftwidth=4<CR>
nmap \m :set expandtab tabstop=2 shiftwidth=2 softtabstop=2<CR>

set smartindent
set autoindent

" sudo omission fix
cmap w!! w !sudo tee >/dev/null %

" Highlight empty whitespaces at the right
highlight WhiteSpaceEOL ctermbg=darkred guibg=lightred
match WhiteSpaceEOL /\s\+$/

" Find cursor:  Highlight current posstion
nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
" Reload vimrc
map <leader>e :e! ~/.vimrc<cr>

"========Plug-ins
call pathogen#infect()
set runtimepath^=~/.vim/bundle/ctrlp.vim

"========Custom Keystrokes

"=== Disable arrow keys
inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>


"=== Initiate Ctrl-P
nmap ; :CtrlPBuffer<CR>
"=== Initiate NerdTree
nmap \e :NERDTreeToggle<CR>
let g:NERDTreeDirArrows=0
let NERDTreeShowHidden=1
"== Clear search highlights
nmap \q :nohlsearch<CR>
"== Switch to next buffer
nmap <C-e> :e#<CR>
"set ff=dos,unix Change file format to avoid ^M line breaks also
"replacing ^M's :%s/CTRL-v ENTER//g

"Alternative Insert Mode exit
imap jj <Esc>
imap ii <Esc>

if $TERM == "xterm-256color" || $TERM == "screen-256color" || $COLORTERM == "gnome-terminal"
      set t_Co=256
endif

if version >= 703
 set colorcolumn=80
endif

let g:Powerline_symbols = 'fancy'
set laststatus=2
