iabbrev teh the
iabbrev cleint client
iabbrev cleints clients
iabbrev ccolroado ccolorado
iabbrev colroado colorado
iabbrev affilaite  affiliate
iabbrev affilaites affiliates
iabbrev affilaite  affiliate
iabbrev affilaites affiliates
iabbrev resutl result
iabbrev unit256 uint256
